In [4]:
import os
import polars as pl
from pyprojroot import here

In [5]:
# load all file name from folder
def load_file_name(folder_path):
    file_name_list = []
    for file in os.listdir(folder_path):
        if file.endswith("txt") and "_" in file:
            file_name_list.append(file)
    return file_name_list


ls = load_file_name(here() / "data/raw")
ls

['RUL_FD001.txt',
 'RUL_FD002.txt',
 'RUL_FD003.txt',
 'RUL_FD004.txt',
 'test_FD001.txt',
 'test_FD002.txt',
 'test_FD003.txt',
 'test_FD004.txt',
 'train_FD001.txt',
 'train_FD002.txt',
 'train_FD003.txt',
 'train_FD004.txt']

In [6]:
def load_one_df(
    file_name,
    col_ls=(
        ["UNIT_NUM"]
        + ["CYCLE"]
        + ["OS" + "_" + str(i) for i in range(1, 4)]
        + ["SM" + "_" + str(i) for i in range(1, 22)]
    ),
):
    df = pl.read_csv(
        str(here()) + "/data/raw/" + file_name, separator=" ", has_header=False
    )
    df = df.select(
        pl.all().exclude([col for col in df.columns if df[col].null_count() == len(df)])
    )

    if len(df.columns) >= len(col_ls):
        df.columns = col_ls
        df = df.with_columns(pl.lit(file_name).alias("FILE_NAME"))
    else:
        df.columns = ["RUL"]
        df = df.with_row_index("UNIT_NUM", 1)

    return df

In [7]:
df_ls = [load_one_df(i) for i in ls]

In [8]:
RUL_1 = df_ls[0]
RUL_2 = df_ls[1]
RUL_3 = df_ls[2]
RUL_4 = df_ls[3]

RUL_1 = RUL_1.rename({"RUL": "MAX_RUL"})
RUL_2 = RUL_2.rename({"RUL": "MAX_RUL"})
RUL_3 = RUL_3.rename({"RUL": "MAX_RUL"})
RUL_4 = RUL_4.rename({"RUL": "MAX_RUL"})

test_1 = df_ls[4]
test_2 = df_ls[5]
test_3 = df_ls[6]
test_4 = df_ls[7]

train_1 = df_ls[8]
train_2 = df_ls[9]
train_3 = df_ls[10]
train_4 = df_ls[11]

# RUL

In [9]:
train_1 = train_1.with_columns(pl.col("CYCLE").max().over("UNIT_NUM").alias("MAX_RUL"))
train_2 = train_2.with_columns(pl.col("CYCLE").max().over("UNIT_NUM").alias("MAX_RUL"))
train_3 = train_3.with_columns(pl.col("CYCLE").max().over("UNIT_NUM").alias("MAX_RUL"))
train_4 = train_4.with_columns(pl.col("CYCLE").max().over("UNIT_NUM").alias("MAX_RUL"))

test_1 = test_1.join(RUL_1, on="UNIT_NUM", how="left")
test_2 = test_2.join(RUL_2, on="UNIT_NUM", how="left")
test_3 = test_3.join(RUL_3, on="UNIT_NUM", how="left")
test_4 = test_4.join(RUL_4, on="UNIT_NUM", how="left")

In [10]:
train_1 = train_1.with_columns((pl.col("MAX_RUL") - pl.col("CYCLE")).alias("RUL"))
train_2 = train_2.with_columns((pl.col("MAX_RUL") - pl.col("CYCLE")).alias("RUL"))
train_3 = train_3.with_columns((pl.col("MAX_RUL") - pl.col("CYCLE")).alias("RUL"))
train_4 = train_4.with_columns((pl.col("MAX_RUL") - pl.col("CYCLE")).alias("RUL"))

test_1 = test_1.with_columns((pl.col("MAX_RUL") - pl.col("CYCLE")).alias("RUL"))
test_2 = test_2.with_columns((pl.col("MAX_RUL") - pl.col("CYCLE")).alias("RUL"))
test_3 = test_3.with_columns((pl.col("MAX_RUL") - pl.col("CYCLE")).alias("RUL"))
test_4 = test_4.with_columns((pl.col("MAX_RUL") - pl.col("CYCLE")).alias("RUL"))

# Concat

In [11]:
train = pl.concat([train_1, train_2, train_3, train_4])
test = pl.concat([test_1, test_2, test_3, test_4])

In [13]:
train

shape: (160_359, 29)
┌──────────┬───────┬─────────┬─────────┬───┬─────────┬─────────────────┬─────────┬─────┐
│ UNIT_NUM ┆ CYCLE ┆ OS_1    ┆ OS_2    ┆ … ┆ SM_21   ┆ FILE_NAME       ┆ MAX_RUL ┆ RUL │
│ ---      ┆ ---   ┆ ---     ┆ ---     ┆   ┆ ---     ┆ ---             ┆ ---     ┆ --- │
│ i64      ┆ i64   ┆ f64     ┆ f64     ┆   ┆ f64     ┆ str             ┆ i64     ┆ i64 │
╞══════════╪═══════╪═════════╪═════════╪═══╪═════════╪═════════════════╪═════════╪═════╡
│ 1        ┆ 1     ┆ -0.0007 ┆ -0.0004 ┆ … ┆ 23.419  ┆ train_FD001.txt ┆ 192     ┆ 191 │
│ 1        ┆ 2     ┆ 0.0019  ┆ -0.0003 ┆ … ┆ 23.4236 ┆ train_FD001.txt ┆ 192     ┆ 190 │
│ 1        ┆ 3     ┆ -0.0043 ┆ 0.0003  ┆ … ┆ 23.3442 ┆ train_FD001.txt ┆ 192     ┆ 189 │
│ 1        ┆ 4     ┆ 0.0007  ┆ 0.0     ┆ … ┆ 23.3739 ┆ train_FD001.txt ┆ 192     ┆ 188 │
│ 1        ┆ 5     ┆ -0.0019 ┆ -0.0002 ┆ … ┆ 23.4044 ┆ train_FD001.txt ┆ 192     ┆ 187 │
│ …        ┆ …     ┆ …       ┆ …       ┆ … ┆ …       ┆ …               ┆ …       ┆ …   │
│ 249      ┆ 251   ┆ 9.9998  ┆ 0.25    ┆ … ┆ 17.5234 ┆ train_FD004.txt ┆ 255     ┆ 4   │
│ 249      ┆ 252   ┆ 0.0028  ┆ 0.0015  ┆ … ┆ 23.7151 ┆ train_FD004.txt ┆ 255     ┆ 3   │
│ 249      ┆ 253   ┆ 0.0029  ┆ 0.0     ┆ … ┆ 23.827  ┆ train_FD004.txt ┆ 255     ┆ 2   │
│ 249      ┆ 254   ┆ 35.0046 ┆ 0.84    ┆ … ┆ 9.0774  ┆ train_FD004.txt ┆ 255     ┆ 1   │
│ 249      ┆ 255   ┆ 42.003  ┆ 0.84    ┆ … ┆ 6.4341  ┆ train_FD004.txt ┆ 255     ┆ 0   │
└──────────┴───────┴─────────┴─────────┴───┴─────────┴─────────────────┴─────────┴─────┘

In [14]:
test

shape: (104_897, 29)
┌──────────┬───────┬─────────┬─────────┬───┬─────────┬────────────────┬─────────┬──────┐
│ UNIT_NUM ┆ CYCLE ┆ OS_1    ┆ OS_2    ┆ … ┆ SM_21   ┆ FILE_NAME      ┆ MAX_RUL ┆ RUL  │
│ ---      ┆ ---   ┆ ---     ┆ ---     ┆   ┆ ---     ┆ ---            ┆ ---     ┆ ---  │
│ i64      ┆ i64   ┆ f64     ┆ f64     ┆   ┆ f64     ┆ str            ┆ i64     ┆ i64  │
╞══════════╪═══════╪═════════╪═════════╪═══╪═════════╪════════════════╪═════════╪══════╡
│ 1        ┆ 1     ┆ 0.0023  ┆ 0.0003  ┆ … ┆ 23.3735 ┆ test_FD001.txt ┆ 112     ┆ 111  │
│ 1        ┆ 2     ┆ -0.0027 ┆ -0.0003 ┆ … ┆ 23.3916 ┆ test_FD001.txt ┆ 112     ┆ 110  │
│ 1        ┆ 3     ┆ 0.0003  ┆ 0.0001  ┆ … ┆ 23.4166 ┆ test_FD001.txt ┆ 112     ┆ 109  │
│ 1        ┆ 4     ┆ 0.0042  ┆ 0.0     ┆ … ┆ 23.3737 ┆ test_FD001.txt ┆ 112     ┆ 108  │
│ 1        ┆ 5     ┆ 0.0014  ┆ 0.0     ┆ … ┆ 23.413  ┆ test_FD001.txt ┆ 112     ┆ 107  │
│ …        ┆ …     ┆ …       ┆ …       ┆ … ┆ …       ┆ …              ┆ …       ┆ …    │
│ 248      ┆ 277   ┆ 41.9991 ┆ 0.8401  ┆ … ┆ 6.262   ┆ test_FD004.txt ┆ 26      ┆ -251 │
│ 248      ┆ 278   ┆ 20.0026 ┆ 0.7005  ┆ … ┆ 14.6486 ┆ test_FD004.txt ┆ 26      ┆ -252 │
│ 248      ┆ 279   ┆ 34.9988 ┆ 0.8413  ┆ … ┆ 8.8389  ┆ test_FD004.txt ┆ 26      ┆ -253 │
│ 248      ┆ 280   ┆ 20.0027 ┆ 0.7     ┆ … ┆ 14.6887 ┆ test_FD004.txt ┆ 26      ┆ -254 │
│ 248      ┆ 281   ┆ 35.0075 ┆ 0.8402  ┆ … ┆ 8.8502  ┆ test_FD004.txt ┆ 26      ┆ -255 │
└──────────┴───────┴─────────┴─────────┴───┴─────────┴────────────────┴─────────┴──────┘